apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-ha
  labels:
    app.kubernetes.io/name: jenkins-ha
    app.kubernetes.io/part-of: devops-platform
    pod-security.kubernetes.io/enforce: baseline
