apiVersion: v1
kind: Namespace
metadata:
  name: myapp
  labels:
    name: myapp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST:    "placeholder-override-in-overlay"
  DB_NAME:    "myapp"
  REDIS_HOST: "placeholder-override-in-overlay"
