apiVersion: v1
kind: Namespace
metadata:
  name: prod-workloads
  labels:
    security.slsa.dev/enforce: "true"
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/warn: "restricted"
