apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: myapp-dev
spec:
  replicas: 1   # save cost in dev
  template:
    spec:
      containers:
        - name: api
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
