apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1      # save cost in dev
  template:
    spec:
      containers:
        - name: api
          env:
            - name: NODE_ENV
              value: development
            - name: LOG_LEVEL
              value: debug
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
